ALTER TABLE "InboxContact" ADD COLUMN IF NOT EXISTS "linkedinUrl" TEXT;
ALTER TABLE "InboxContact" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "InboxContact" ADD COLUMN IF NOT EXISTS "contacted" BOOLEAN;
