-- Expand UserAsset types for library documents (portfolio, references, etc.)
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'PORTFOLIO';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'WRITING_SAMPLE';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'REFERENCE';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'CERTIFICATION';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'TRANSCRIPT';
