ALTER TABLE "Profile"
ADD COLUMN IF NOT EXISTS "prioritizedRoles" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "Profile"
ADD COLUMN IF NOT EXISTS "prioritizedCategories" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "Profile"
ADD COLUMN IF NOT EXISTS "deprioritizedCategories" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
